### ISSUE TITLE
How to check in?

### ISSUE THREAD

**Issue by tvvocold** [FZUG/members#1]

**Comment by alick** [comment]
I would like it to be just a markdown table. Two columns: github username, and fas username.
Can you init it?

After that, everyone should send pull request to add or change it. Direct push should be forbidden.

**Comment by tvvocold** [comment]
Done.

**Comment by tvvocold** [comment]
@alick9188 
还有个问题：谁来负责 merge?

**Comment by Endle** [comment]
[**@alick9188**](https://github.com/alick9188) commented on [2015年4月9日 GMT+8下午9:34](https://github.com/FZUG/members/issues/1#issuecomment-91232589):

> I would like it to be just a markdown table. Two columns: github username, and fas username.
> Can you init it?
> 
> After that, everyone should send pull request to add or change it. Direct push should be forbidden.

能不能再多几行？
比如真实姓名，邮箱，在组中的任务？

**Comment by tvvocold** [comment]
@Endle 
”组中任务“这个不好定。另外太多信息不太好吧，隐私呢?
（这个花名册主要是为了确定 github.com/FZUG 没有外人，关联了 Github 和 FAS 之后目标达成，其他内容的话，不建议加。“更多信息”也可以由成员自愿在 FAS 的 wiki 里自行添加。）

**Comment by Endle** [comment]
[**@tvvocold**](https://github.com/tvvocold) commented on [2015年4月10日 GMT+8上午10:00](https://github.com/FZUG/members/issues/1#issuecomment-91400578):

> @Endle 
> ”组中任务“这个不好定。另外太多信息不太好吧，隐私呢?
> （这个花名册主要是为了确定 github.com/FZUG 没有外人，关联了 Github 和 FAS 之后目标达成，其他内容的话，不建议加。“更多信息”也可以由成员自愿在 FAS 的 wiki 里自行添加。）

恩，你说的也对。
而且有了 Github 和 FAS 帐号，其他的信息其实也能找到...

**Comment by alick** [comment]
@tvvocold 只要不是自己本人merge就行
