### ISSUE TITLE
How can I join FZUG Community

### ISSUE THREAD

**Issue by LanstonWu** [FZUG/members#34]
I am Fedora 25 user,installed it on my laptop thinkpad P50 for a half year,use it study and work,my work is database,also have data analysis experience,better on Python and shell program,I also interesting in C and Linux,how can I join FZUG community?

**Comment by alick** [comment]
Hi! Welcome! It's easy. Just [register an Fedora Account](https://admin.fedoraproject.org/accounts) and start [contributing](http://whatcanidoforfedora.org).

If you want to be added to the roster, you need to have a user page on Fedora Wiki for now, which requires you to be in one of the various teams in Fedora, such as infra, docs, website, translator, ambassador, etc.

Let us know if you have questions.

**Comment by alick** [comment]
Closing issue. Reopen if you feel necessary.
