### ISSUE TITLE
add alipay and paypal column

### ISSUE THREAD

**Issue by 1dot75cm** [FZUG/members#35]
前几天，想到可不可以在 members 库里面，为每个成员加一个 `Alipay` 和 `Paypal` 列， 这样如果想要为某个成员捐助，挺方便的。而且支付宝是实名制，这样大家也互相认识了。 @alick

**Comment by alick** [comment]
不好意思，我持反对意见。我希望这个列表保持 KISS 原则。想要添加更多信息的成员总是可以在他自己的用户页面等地方添加。

**Comment by 1dot75cm** [comment]
喔，也对，建议大家都加上 ：）
